---
sidebar: sidebar 
permalink: xcp/xcp-bp-troubleshooting.html 
keywords: troubleshooting, problems, error 70, 
summary: Questa sezione fornisce indicazioni per la risoluzione dei problemi relativi alla migrazione dei dati tramite NetApp XCP. 
---
= Risoluzione dei problemi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione fornisce indicazioni per la risoluzione dei problemi relativi alla migrazione dei dati tramite NetApp XCP.



== Errore 1: XCP non riuscito con errore nfs3 70: errore filehandle obsoleto nel file xcp.log

*Ragione e guida.*

Montare la cartella di origine e verificare che la cartella esista.  Se non esiste o se è stato rimosso, riceverai un `stale filehandle` errore, nel qual caso puoi ignorarlo.



== Errore 2: il volume di destinazione NFS NetApp ha spazio, ma XCP non è riuscito con errore nfs3 28: spazio esaurito sul dispositivo

*Ragione e guida.*

. Controllare lo spazio del volume di destinazione NFS eseguendo il comando `df` comando o controllo della memoria.
+
....
root@workr-140: USER3# df -h /xcpdest
Filesystem                 Size  Used Avail Use% Mounted on
10.63.150.127:/xcpsrc_vol  4.3T  1.7T  2.6T  40% /xcpsrc_vol
....
. Controllare gli inode nel controller di archiviazione.
+
....
A800-Node1-2::> volume show -volume xcpdest -fields files,files-used
vserver        volume  files    files-used
-------------- ------- -------- ----------
A800-Node1_vs1 xcpdest 21251126 21251126
A800-Node1-2::>
....
. Se si utilizza inode, aumentare il numero di inode eseguendo il seguente comando:
+
....
A800-Node1-2::> volume modify -volume xcpdest -vserver A800-Node1_vs1 -files 40000000
Volume modify successful on volume xcpdest of Vserver A800-Node1_vs1.
A800-Node1-2::> volume show -volume xcpdest -fields files,files-used
vserver        volume  files    files-used
-------------- ------- -------- ----------
A800-Node1_vs1 xcpdest 39999990 21251126
A800-Node1-2::>
....

